### ISSUE TITLE
ViaMCP error during mapping loading of Protocol1_13To1_12_2

### ISSUE THREAD

**Issue by Thereallo1026** [LaVache-FR/ViaMCP#16]
```
14:34:46.499
game
java.util.concurrent.CompletionException: java.lang.RuntimeException: Missing type parameter.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1621)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.RuntimeException: Missing type parameter.
	at com.viaversion.viaversion.libs.gson.reflect.TypeToken.a(Unknown Source)
	at com.viaversion.viaversion.libs.gson.reflect.TypeToken.<init>(Unknown Source)
	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.data.MappingData$1.<init>(Unknown Source)
	at com.viaversion.viaversion.protocols.protocol1_13to1_12_2.data.MappingData.a(Unknown Source)
	at com.viaversion.viaversion.api.data.MappingDataBase.h(Unknown Source)
	at com.viaversion.viaversion.api.protocol.AbstractProtocol.n(Unknown Source)
	at com.viaversion.viaversion.protocol.ProtocolManagerImpl$$Lambda$84/1073751644.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1618)
	... 3 more
  <log4j:Event logger="ViaMCP" timestamp="1631342086498" level="INFO" thread="Via-Mappingloader-7">
    <log4j:Message><![CDATA[Loading 1.13 -> 1.12 mappings...]]></log4j:Message>
  </log4j:Event>
14:34:46.499
monitor
Process Monitor
XML_ERROR_PARSING
```

**Comment by NathanKassab** [comment]
The repo is outdated and hasn't been updated in a long time
