### ISSUE TITLE
class def not found viainjector

### ISSUE THREAD

**Issue by Juloup78** [LaVache-FR/ViaMCP#17]
hi, on eclipse the client work fine with viamcp but when i export my client and launch it in the official minecraft launcher it crash with this in my crash report: ---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 30/10/21 10:30
Description: Initializing game

java.lang.NoClassDefFoundError: com/viaversion/viaversion/api/platform/ViaInjector
	at juloup.Client.startup(Client.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:560)
	at net.minecraft.client.Minecraft.run(Minecraft.java:395)
	at net.minecraft.client.main.Main.main(Main.java:114)
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.api.platform.ViaInjector
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 4 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Stacktrace:
	at juloup.Client.startup(Client.java:60)
	at net.minecraft.client.Minecraft.startGame(Minecraft.java:560)

-- Initialization --
Details:
Stacktrace:
	at net.minecraft.client.Minecraft.run(Minecraft.java:395)
	at net.minecraft.client.main.Main.main(Main.java:114)

-- System Details --
Details:
	Minecraft Version: 1.8
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 51050456 bytes (48 MB) / 201326592 bytes (192 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	Launched Version: Skidware
	LWJGL: 2.9.1
	OpenGL: Intel(R) UHD Graphics 600 GL version 4.6.0 - Build 27.20.100.8729, Intel
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Very likely; Jar signature invalidated
	Type: Client (map_client.txt)
	Resource Packs: [4x4 and more by Sharpness Sword]
	Current Language: English (US)
	Profiler Position: N/A (disabled)

**Comment by hiderikzki** [comment]
Hi! This is an old version of ViaMCP, please move to the newer one and follow the readme (fixed exporting method at bottom) https://github.com/Foreheadchann/ViaMCP-Reborn
