### ISSUE TITLE
io.netty.channel.ChannelInitializer channelRegistered | 1.8.8

### ISSUE THREAD

**Issue by NaNonnI** [LaVache-FR/ViaMCP#6]
mars 23, 2021 11:38:46 PM io.netty.channel.ChannelInitializer channelRegistered
AVERTISSEMENT: Failed to initialize a channel. Closing: [id: 0xe192654e]
java.lang.ExceptionInInitializerError
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.registerPackets(ProtocolPipeline.java:28)
	at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:54)
	at us.myles.ViaVersion.api.protocol.Protocol.<init>(Protocol.java:42)
	at us.myles.ViaVersion.api.protocol.SimpleProtocol.<init>(SimpleProtocol.java:11)
	at us.myles.ViaVersion.api.protocol.ProtocolPipeline.<init>(ProtocolPipeline.java:20)
	at net.minecraft.network.NetworkManager$5.initChannel(NetworkManager.java:389)
	at io.netty.channel.ChannelInitializer.channelRegistered(ChannelInitializer.java:69)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRegistered(AbstractChannelHandlerContext.java:158)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRegistered(AbstractChannelHandlerContext.java:144)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRegistered(DefaultChannelPipeline.java:732)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.register0(AbstractChannel.java:442)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.access$100(AbstractChannel.java:374)
	at io.netty.channel.AbstractChannel$AbstractUnsafe$1.run(AbstractChannel.java:418)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException
	at us.myles.ViaVersion.api.protocol.ProtocolRegistry.registerBaseProtocol(ProtocolRegistry.java:189)
	at us.myles.ViaVersion.api.protocol.ProtocolRegistry.<clinit>(ProtocolRegistry.java:84)
	... 17 more

**Comment by NaNonnI** [comment]
Oh, nevermind, just init it
